[[Ninja]]
arch = "aarch64"
git-tree-sha1 = "bd22dd5450aec17847f0d4ea736da5973f620455"
os = "macos"

    [[Ninja.download]]
    sha256 = "cd68b4e689f6034a360eaab81ddc3bc0ce239ecf7d57c92758bce90b3945dd6c"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.aarch64-apple-darwin.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84952cdcdb638eac2e51ddd731dc7f0a5e9fe290"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "a67f97c30360100933100c8aec98af422e77b75ae8599625db19d4ed8506f782"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57ab01127a4a57965d1092be68c08c478831f7d5"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "d5e3da812121a02618760da63d218c1a48b0bdb51b1938e036715cb2ea371162"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3d81b05f3d654d794520d81ad8eee4729551f45"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "76cc6e2ac095c0e4c95c38e10ec6a77bf264c4daacee963b674eba13d2560e23"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.aarch64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aeffa2c83ee378b921391d08a43e58f24724807d"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "443d02c742d9d6a2d850d46869f7b8b8387b453601ccb18c4b53f156d76c7fc7"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.aarch64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d417c18c89344020d6cb9196162f14bcab8e6b7"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "f955c8e8171455f217c3746c66f7975a4e34ea4a6f94f9fb6d326817810f501a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a76ca2c6b19b72e088d0d6f30488daff4551a3b"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "91a10d1952bdac7d4f2d3989599ac25fcfa87b9c7cc7954a6efadddef49a6b20"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccfe4f2409b0d32388d0cc5e8e84c8998934dabe"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "2940ab88d4db4f69ec3d20f670a3fa123adb8e96709f223b8c84a5e55e62b7b7"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb3f284bbc665245e79e8f4bcd1be8fa5dc6a67e"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "c7a9f910569812fb835ad4873290429580631d26d971c82aafbafd0c7e9ead2f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63a5ef4eb6a20383bd230d6bccf2e368ad6a3592"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "3bd1dfdc99b5054acc408cb82fb46781278865047deebb32dc1375b43eab5b39"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17678bc6135147c1ee8ca94a020ab39b7cccde3b"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "7f4ac361cd7e32a93eb0430b98a624090c42b1cd1ad511dc8385f0ef282ef328"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6adcfc3c1f500db106fbc57709521171ce96b9ab"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "564ce04eefa02152684d2814302315557e60ab9a09c2e6ed0a2dac8bf9f2be7e"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43a9e4e806c61741e5ddd7d99003296bcb092d8f"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "b97d75945b737377928a8f0b986401dad47e6e1047e6b400cb26c5134fccb306"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5141f9d14eff8129e17610decfc71f6644d2bec"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "d389907ba2e9ec772e50c9135fa0ea1923b4fd6f3c6593e32befa59901ba85be"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.i686-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b1d2b666c1949901f0739a91422eacf3836dfc1"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "53515e485b9bb4ee52047b42533e53a04ab870013dc811b6cf1f602a6a01b642"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.i686-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "071e1c8dcd92d8e4c755cedf12b08a253c0e107c"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "1147ac33213c81c225fbb0926c8b1e5b7d06c2476897c5a3dd49763bc4a622c6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.i686-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5d5d1471d7b9d85d372c9f0f3a494996d4c828"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "4d7b71d06a6e6af6b14d30630edaf4dbb1486d0c83c3c34f6c31479d6b39bcce"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.i686-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d6a476720aef74d97d4c97380c84e85ae585aed"
os = "windows"

    [[Ninja.download]]
    sha256 = "d31a3ca33ce2e8aed4f19faf537aaf89c4131e581fc2f78ae8404509ed17b3ea"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.i686-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29e80e18544e386c78cbad9e3cfbcb5b50efad85"
os = "windows"

    [[Ninja.download]]
    sha256 = "0a61c9f598528ea57fd07ae898fa2f1db795421108034ae9e1f1e1590cb41b0a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.i686-w64-mingw32-cxx11.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e57e1533a08057594111beff5bd0f980f862aadf"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "6a70894f11d6a66b2d4919a34e386f2394698d40d9087c5ca2a61ca58fcfb3e4"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba37b1d46856a403db6e2ad2f58d6beab1f712af"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "702a258fd0c87df15b0b32739c36d17e26c6d81f33d376c0277f5492117851d8"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "25edbda4767e4a250b587a7f0febab78ab676510"
os = "macos"

    [[Ninja.download]]
    sha256 = "3f032f11754317519bd8264b7b1cbbda22fd03651fb8a899f0d9f836d931f76f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-apple-darwin.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d5f49947076489de75af446a0b07264c3564d12"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "e0c832dc363b6497ecfd3ed3604ed11564c3dd6c1cc122d7abb5463fe5141cc9"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74ab1140130bacfe76fcfdc4998bba73d0b6bf71"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "dc18e577d8af3c02deffa1f9b1cc87beeedab1e1bc849e4f2be14860565fa05a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38c9dd0563a43e6395adb7502e1185e687df7442"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "248cccb92b9e05845fd08924245b2a3f093f113c2162e13084aa0cb0c5294201"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "320742d1500f55a94627061b6b307fd088995e21"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "3b06c7d4a568f77a6ee74b70f56ce29fc24228b6ec9d06caa2a8791f2d75ac85"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "6df0ef7e0a5f7baee60dc8c9dde88b027c868bca"
os = "freebsd"

    [[Ninja.download]]
    sha256 = "886b852760cbbd97edebb478da02c47c37c468ac8556347ee1a162c16eafe59c"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-unknown-freebsd.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6842d0584a3e640c64644cd162f5f842b1701ab"
os = "windows"

    [[Ninja.download]]
    sha256 = "375406748a54a7880d85c6fdbc19224cd074bed935a2c6e13c22eeaeb1726816"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "194e5f105bd17649cfac206a1e2262273195e5bd"
os = "windows"

    [[Ninja.download]]
    sha256 = "ce83306def663d26ea1905d93d5b54230f066351737ac64011e0d4f3ab432fe6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.0+0/Ninja.v1.12.0.x86_64-w64-mingw32-cxx11.tar.gz"
