[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dfda93295f7028ee3a95d839d963f31a10b4a8a"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "77f60902c67ad640997a39da56e8e6d05bf6d905e31cc8e4736061e55a65612d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f2aec21e5348b71bc956a1c6c64f8b0f636ee76"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "21f16dc2fdc2f336347b9ca6ddca7f287c45b67589ba7a3aa94452e34b6645ee"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e6f369ca979e9c71e444d55b3b09eb6e956670d"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "5dd09696ad3f9cfe31d0c634bd36086457cb6a6def44f14a1b8aba1a1e62cec5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.aarch64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7e10944666caeeb62c5bd5d3a137607e098400c"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "4890bfc0aad0d0fc3e4a22ddb20af5167890021c9614d241cbd71385f6b8c8d0"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06398a7291b0b6afb1f2b7fceb3bfdc5ab5c134f"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "29bdaa23f4bc3ea5efc42968fe4202895ae0a799f4d813f4e2417b32e92ef082"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50b1e2bdaae269839220727adb05f7db88db0c72"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "56c259851875c4023b84ce43d97e10772b4ebeb6eebc21395fd252c90a07bb3d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a132a750b99f1023c0abd1dc326e34864b2ed760"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "5d8a1fdb7a240fcbaccd04cff76118c95c619361b5485b24955518de33969d27"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78a937fd42f84ceb77ffb2af8da46e0cfa692460"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "edc82344b9be4468099614280e32e097348320a699155bbe20580fb6521e050f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "273fa55719b3bfaa306ab0bbea942392c8b054f0"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "21d571314a097b66b8368d5b6f8e85350814cd5b14ef733f4daee055a262d7f9"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.i686-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d89a20956b8f7542773cc4467c89f1b84ab2f27"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "515c0d6b84bbe644878848f2f85bf11b6458987b966b15b83b591d3e3e83d247"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a608707f515b829e45aa29be5149629880c9e827"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "813c3e60377f7cae636328e9c97c819eb761d15b27aae92dc21fbd6ed9fc678c"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.i686-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa42518f3d0b41003922f3b829286fb29bee6860"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "b97fbfd70b7fc3c033a0b2b42e8da3a703866d7cc040a8fe0cddb1439415bd54"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.i686-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a09e2d8b29d38c8fb93cf661e373c69fddd715ad"
os = "windows"

    [[Ninja.download]]
    sha256 = "05791eb3158710ff33fc24ce44909b2e8416e813e4a60b367b7e9a830c0c2f3c"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.i686-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e6b383173b237207bfe8d1ef4d0752d6fc432f8"
os = "windows"

    [[Ninja.download]]
    sha256 = "8a529730fdb0584f1f50f41c0ffb512242be547a536d72353ca769dc8acb9681"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "788c5b129765f2730d9d15a94a2b1903549ba0a8"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "9b936bbc638c029ecb6c0f7059927cd712251f1d9c1a604734119e2160ac2436"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b26e631b3f847191a3b43b6d466fa8cc7c0851a"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "7f6890ba75f23cb8c686d64e89d6f3eba4d298921d1a072d689d6d24fdca233d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "d382b663a4d76e53800001a886a6a092868eb0b6"
os = "macos"

    [[Ninja.download]]
    sha256 = "b9ad7ca1a2625fa975f4353b32a174b4bff88002cbc9007f1f7f38a52c40902b"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-apple-darwin.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78caf8a6a38da207bdf444549cd63dc7bc7100ae"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "8b5317d4665867f1cfc8f96b04d5b2805b8752b1a30101c9fb240c2d7aed9e88"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c691067888ecaefb0c9292627d85d39f670a02c3"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "5243ec8bb3c94fd1c66f546579c4c2c95194e5d0b637d135e93f5c47ae0c78c5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1199e29a3e78a6baf77b45870b2025a0c1b4d727"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "e536245647a743660e6d72c168a7a652e642d351316434fb152efb7b31e955b5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b708b6c3eb1d159ab4d4121ba20acec01b812304"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "53146cfaa3df838f7d4745e7d0e4931ca5971a0424be34c35454764903cc1983"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "f797a2f36c93de4c45237a74604e2f32090cea8e"
os = "freebsd"

    [[Ninja.download]]
    sha256 = "103865556833a7ad1e364a7bdb4ab57a07d23c54233331b76563b19bc01062e6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-unknown-freebsd.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e998682abe3529f65c810c60b7f524eddb734f5"
os = "windows"

    [[Ninja.download]]
    sha256 = "794603f467fd47462b7cbee78b6d0ce469fe08ad20f583601e72b7925f3743d9"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29643c7c1faee753288fdae4d320ff9ffdef998d"
os = "windows"

    [[Ninja.download]]
    sha256 = "3fb3e7257f4b4fa2e762ce7e36eb5f7f2f9608b0b2c0dacb3e2410c3f559c664"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.2+0/Ninja.v1.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
