[[Ninja]]
arch = "aarch64"
git-tree-sha1 = "c6798e93a94c588c9e12a675cbb9d37946b887f0"
os = "macos"

    [[Ninja.download]]
    sha256 = "6ff63394997aa91a6ef9109074687ac73950afa87e22bab4fbeeb1e1b726edda"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.aarch64-apple-darwin.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2243c10cdeb052190c2a7f3a95d088672878c43d"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "b4a5c0dc8a1559bb4ecf3f16b831ee6d695e99ad0a3a59ee7ba91d4c615c356a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67a44a5bea3126d8b2d4cde05ccb8bed5eebf1af"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "aef4fbcca33b2919eaa4df14c4f0094f71f2371f18ef45eb8d07056e25469d08"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ef78debc9f769655bc46b7ddfd72055e9327deb"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "6a36d8e5e4ad7ee4acf8ff09b9e5623895eb9156754454cdad08dd140ee2c801"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.aarch64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0a3a867899abb02474ebcc1baf57dc5d32fbc02"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "ae0c5c3f3649945e229b59cd7aef8991f4f6a1cdb5a9a973ba36ce49a4f4a2a2"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.aarch64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6296ee9cd53208da4a8d2f07f102f02372cf4a5f"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "ea8067a14bd4d22734dd901e399f38a52950bce043e87188d0a9140ab4cb71ff"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "885ebc69a73b10ee7ea6ceae8b4877a5e99f1ae8"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "765b66933004d80aa7a0ee5e442d448bd881dbaf94762ec60504aa1e501f062e"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "880d5378027417a5d0662d2d8f4143093cb303f2"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "f91ae6b38da516d96cbecd23c0774aabd4aa8e32f87f19ede7311913eb19e9c5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db88679caaa952d549b008180f8ced25b94c5619"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "5248e0b28b76709a861ce7701a9b7a1db1eb272c1400022c9a959157cb5a074f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f24e62df5ac9b7b86a4790a599c6be003695725a"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "4c356571cc987b6f1daa177e939fc27783c8d8768bdf06b9d62b5dee26c3d020"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c92f72fbc989d3d4813210fdd7f0bafc4e001dad"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "02797975180543c795c7e16b958b002ba22f9d41aa4d362765ab6464b37dceb6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1f7bf92fd02548cb0954e79372d128520a46625"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "8be532ee6a2bfed20ea5168f138f57cd159e0a469ea99f8a00349571f0abe686"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e10cab9e66ea3563940ca2cf6d3e6c10a2f800c"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "16010c644629084f8df469f0bf7396cfcae8bcbf4dc1b7d3193b33b84c7e24ed"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9203f963e5ec7748327becd00294bf6597705511"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "31ef0206147f23841389fddcf5d716f55882f6cf07a0d8fd16cf8a5aa02570e0"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.i686-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "754b1e568d0022590cf19e789985e49110b35651"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "5b6d9bc808c487b2d5d6fe3a9d62c8203255d3255ad2fdb786864a102a39367e"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.i686-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "723bac1c07314c986a2f4d5c0bbc5d08a7fb50f7"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "1bb61fa3c328949a144231ae0f452c6d050ee7b85b93bb01d1d9e3c97b7c17b4"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.i686-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c243f59985c8c257472a039e702a46f6e063962"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "de6b8516ba17f7c7399843fc3919d8f7e60e7a91906ec27c081fe76221cf908e"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.i686-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a220106b96388a5b46128b0a1634879d5870ebb5"
os = "windows"

    [[Ninja.download]]
    sha256 = "a6a906b56904f2cbe4f857c336639fdd4e4fe741023c14adc7f62307a33ac4fe"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.i686-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18beeb7d3feeb1a1a00fd67d7e5541edd1bfefb3"
os = "windows"

    [[Ninja.download]]
    sha256 = "ec7c180b71b260428835bc836444bc76604a54baaa3f2c784154b10e3ca26ba1"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.i686-w64-mingw32-cxx11.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d4cdaf8f2692b712978abd64706d6a3f74f04d2"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "4a608952677fe8104dd8fb3d6db080bb947cfb4c470ead2052c509f2eacf2f81"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a3b326b4c10ca4d4bb9d296b97039551111bbce"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "65e8ee5039e964504d3355daa14e1826b35e91a7aea51b53fe82040514d7f570"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "a49c64b37869fd990e211086f265bbe65f85e157"
os = "macos"

    [[Ninja.download]]
    sha256 = "67d71718ee4341eed2e1b93a34a2e3a5f9a8d70a1bb0c7f30eadedea0377e6d1"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-apple-darwin.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5192ea4a064da049a62a374273ef194b0c3387b1"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "a46d8852cecbb7a6e3b1b285aa5fbb8a1ae5c5eb7deffdfc11c7a0e6cad81d31"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5eb24da83018471ef0c91e44bcc0464f280a7d0"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "6b84bdfbb504cf310b25e835a912679162eb7ad760f5547dbc69a638ccdf19ec"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e92abbb211790c503c6ae0cd9924cd3592932e3"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "1d5e1a0fb768bd0908863b95dbeabc4cff186578b0d7b8b7f5eb115e8601a10f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d60d78c46649721969bc52d0039771489a7a3d02"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "47fe794a6024f33fe8314d5f0a929b194d9385c98736fe61d1bf11f8c2a4d059"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "242fa524931b711f82e894423b1649660d28a57d"
os = "freebsd"

    [[Ninja.download]]
    sha256 = "e96b570767b7f1287425b0fcac0de16320239ab90abd04d7a9ec1f98ae597b88"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-unknown-freebsd.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c13e8956662e300e23f47a1976695836face450"
os = "windows"

    [[Ninja.download]]
    sha256 = "5880cf27b1258fb6441e2a49e0b4af7f6ffbeb05ea3fc79fe33d1e4e4cb72c3a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ea44897cf4e560dcbbcc881720cde486f95036b"
os = "windows"

    [[Ninja.download]]
    sha256 = "dfdd52bdd38f76203fb247be05aaed403059d27d23d2e2c09a225a3d4379518a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.0+0/Ninja.v1.11.0.x86_64-w64-mingw32-cxx11.tar.gz"
