[[Ninja]]
arch = "aarch64"
git-tree-sha1 = "a15da02145195dc753e4bb8a0792355320b7c4bf"
os = "macos"

    [[Ninja.download]]
    sha256 = "fd2d07203ea4fc31f7561ce7e29984ea90a81e4cd40455c3428f17cd40d15abd"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.aarch64-apple-darwin.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e737a1f27d4f843bbb5205428ec57c54c7bd777"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "049defb1e9a4a002eb6b110bad327a66310c252bb97c6785bbf2c257ba5ba565"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce3c32352fbcd150cc10ee09fae241c8385d1497"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "20076d2c15a13055a881ba03fde82ed5074f88bc3a511e7735e190c7c2c3f6fc"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86cbb54c00959e63d149dfe9bf95db7df5c0b0ef"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "ef105d27da7bc396835d3dba6b8d83f846655ab3791096969ea8a5dca74b1f9d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.aarch64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64095f16038ccf96b5cdf3ee67cfda8092d6983e"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "15d658b2642487964f0558441963b80d95d9230c3550d8c1d642dbc28717cf53"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.aarch64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1337d1f3e8c918e5a94ed280aef7edfb4742ccfd"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "1c2a110a08462d352aec97dd15b30afebb4cf1eade79486c44684325cf7f45c5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc7c070ac36d2ec082b68f0b99cf674d4131aac0"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "59f1d45c2e1a08cd1a322d8b3f8eda005a86ddc3c2353af1bb34ab83c89eb2ec"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86922e6549b99600339a1123bbd1ca5712cd41c4"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "fdfa58f32863cf80dce91fab44c9fbd9f58a977388978397bb89fd4efe8c0bf4"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd62a63893a0c19666159a6a56b4ce7856a61ba5"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "fe1091c1ec2348b7b6d0fe12d865085a6cb90bdc96f5dc1f38b1c0d38cd25202"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc9bd88f535aa8a1a71844cb90b17d249040367d"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "9b74ab938efb305a618d035222cf69562acd2d38a7833a231af6574a1ced6818"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef593f2383d5118fef8829f85618d823b955d6b1"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "7b745ec4d8406639f174c38f55cb45822771cf1167e35abaff7ef7ee4c5d43c7"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5bd7e9ed2b5bcc07a11ec1ec13edd979f8d166d"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "90e346336e4ab15bc6c7511184befad32aa54f32162a1d12029eb1abbd6e318a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb137a4c4500adb6b9f1b6436a052f86fb53cc74"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "313b3d8aee295c289b21ad9d551680f92034ca6b2cc17e31ad5bed299dbc59b6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "226a7b5ed0be0ab61da11fd2e758971ba04544b0"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "964031429e469118e229c2b3205d356284e780f91e5efc71134ee12acc0174ba"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.i686-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8f90feb51c6618ca00c9aa5d1ee510e0562be00"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "5175c3675f8e4daf58717eb7dd89fd0f31f8565b2725326847617c76f4e5c0c8"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.i686-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccf272b64d6bbcaaab80ea6e558d28d603b16b41"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "2fe6cc50cc96560ffd019e2224b7468761f9956702c8d2e1aae1a06923fb727f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.i686-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ff9019ff392adb32ff2a3e7044ccede8575b035"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "b1c5d8f8b179b78fa4194a499466d4516e1e98fd6c060afa52fcab8987785cfb"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.i686-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95b471560d8446d09909a93aca99d19742c5b3fb"
os = "windows"

    [[Ninja.download]]
    sha256 = "6862e9d50e74e946a2f8823f8e24e13e329ca784045f7f3857ec34e3fdf4d64f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.i686-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6216bcefa5a7b55a772e59e423bf4b7e7d96331"
os = "windows"

    [[Ninja.download]]
    sha256 = "e4e2fbc3dfed0e3e5609df824ebfb5d5155d41eb9163e3d10a308a9969921613"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.i686-w64-mingw32-cxx11.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e56ff2a2f089e5027b55035a3498c6393d277a0c"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "e2284f0ad1c2c8cebc2e670750ed81146029ac4e4e8e5c14047491295a4c6259"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f62d17358a1dee607c17f1d76dabf0dd8f942195"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "08a9e9ec27eba856e517de72cdac1142a3800b6c30600d4ec39b4b750eccbb17"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "4f74cc77437142e3a0f3670ce9681b354a921120"
os = "macos"

    [[Ninja.download]]
    sha256 = "54fb2d29c1ed2d1c69f9cbb4b7ae1afaf3d5e2e536eb59616215389a517ec8bb"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-apple-darwin.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be4e258aeae1820c5622e5ef43d0bfec12c700d5"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "60a11f08381ba21a153aee2ce32b7e64eb7ebafe75f417ec97719e6217f9bf69"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a41a93dc439ff608d9e17aa39bbb2b834b68f325"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "b570e89e94feabc5122977adba4dcbb97fb4e35849375d1c50f9a09db4f3b1c4"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62aa5195aaa33977d6d4ff7a8864f7b26e6743a1"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "862e6b06cfe9138cf772ca748631b9443e4a860325e9f390c8d6b9ccd1132cc6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79c860237bebae0e72556a71473b577615ad8078"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "87686b469df60aad1e4a8a5975e10837d8a90e8719be77cdb70104d8eca16aba"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "05535629c2b1f91e6c8c28e048a1dc3665f0e0a4"
os = "freebsd"

    [[Ninja.download]]
    sha256 = "2f81a86642f37954fd5fef62c789be3b090a2e62cc772dd5e854e8c4c512aa78"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-unknown-freebsd.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f88d63ac5f666a355d9c2424fb97f3883ba77c88"
os = "windows"

    [[Ninja.download]]
    sha256 = "3f8d31553c86aafd9d9c7cbaf4bcc0fff7bc42c101d71b686ec0c3360cd341e5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a261b8fe49a22a74f7a1f66d40b2e829d4dd67b"
os = "windows"

    [[Ninja.download]]
    sha256 = "e5851b2cf2d5ac510f0a8f4eae8959f12dfecc7110f4d0236e9f6b604fb09410"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.11.1+0/Ninja.v1.11.1.x86_64-w64-mingw32-cxx11.tar.gz"
