[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aca80ba95cd2e35a8e3cdd136257b6119ce66a56"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "17680a6dd5ec0b446f67d944ac4bcec1cb57279c1cf2457104034704de90843a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29d3dd1910ac30eaedea5e12b99b65b0b9eaad03"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "233fed0ef1214e0a8eac69d607eaea66ad8bfb6b0b405446bca7220483d8c3d2"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd590e6aa243376f41408bfbdfa5621c507a8862"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "b16f081e517f95a0ca0f5b0bd392e709ec32b9224cadb5c62f6a24babc01979b"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.aarch64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "011c68bc2a462b3f6d62d8ee68f72163f49eb014"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "d1793734fe04ec6a0fec437d348889520f03134bca5bb4c7fc5d484907c03b03"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.aarch64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29292493169dc129ca72130ccdc5fe569f2f894f"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "79e5486ed020010ac02a4a4edd57842ac2c37236bf8317c379f6d94b7e7ef720"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "244dd176ffafe8756e70119a3aa9533ea4f92c7f"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "a961ddc5521e22a4b7515c613108f94e92f5946ce1b418677a7bdcf227ff2f62"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ceeebcf01e19a3fac6ad4ec94aa65c864a546f5"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "c901c68804d3884dcc0d2e9be3b31d6b6f97f3fa5756f5124f072850d93a4a82"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d688d77b97c0786ee6841165b2b84e9b4a843e1"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "74f0eee1436800fa349f5d04745f3db137c297577d8a2310469228ec2db16c38"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b58b2e89cbb3ec85781c602b98c52188e7efabd4"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "d11aa0660e563c5f5419df43e8ec5426319549a3418a0114944a36d734b45772"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.i686-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "233bca8bf44e7cfedcf1c44834f83a63fb18ae9e"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "397a9c00357c75b380392b233161c3b36649f00b4ede582230cdeab72bf80a9d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.i686-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adba141db689283f01e02c4c4837a2048cbe599b"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "c33012320ef3713422ea9727caf41f275f8e82bc8be42d3c1f731f78521c743d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.i686-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24762b19b73092fe3110b7b8750cd49c097a788e"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "b4602bab2fde7cb2f198469860424309e961a7fd0ad7d996ffa36f863308c933"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.i686-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8b3c9f2fb87fc0d375fd6094ae5c4efd96d7a9a"
os = "windows"

    [[Ninja.download]]
    sha256 = "aba84e3aab8923bca443ca995e26cd98fe4701fffe4c1ded75a441e672d79648"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.i686-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb098150dd5260f3cff7df1dcbcca69e0f95cf17"
os = "windows"

    [[Ninja.download]]
    sha256 = "0b2257bf4b05631ccd3685e0430e00dff24784ad346be0db7cf2e05139ee2350"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.i686-w64-mingw32-cxx11.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22e25992ddbd746dabaa18a13d5f4e3347991e0f"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "d87d0aeb295af5f464de0e8f08b4c5f480744f9a55af1df60cb55c0064e2ac04"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0482c284281d5f2a7efec727d40d2c8c91342f67"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "da3ab1c655c443dc066170ce185d21388d26c4ec553045c91240a2f932a44e5d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "c8405286ccf70947bc1a3bab0d85ec07bbb22340"
os = "macos"

    [[Ninja.download]]
    sha256 = "524ea048139268899031831a3eb2bbc1bfc1775dea7480a7c9ba4676351d94a1"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-apple-darwin.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26dd10c7c86091489065ea09a6ccec337b6830d4"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "4040c2ba01782131db62ae529ebfed3bbbf45751d568f79d76a61068c9930411"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb60c2a27e78f262f8682a4510387c7bd1e52449"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "a0e0894d7efc526d2cf1b23b424cd4f0d13945bb3ce89dfbdc30d84a11746ed8"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2b48e17b78fee74c81c41106a462c1ed22b2a8f"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "c8777ce44273c50442ea421d84be51139cf0c38681fa74442e77b6808c58b332"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c1db061f5a22d3f298cb108037bf79c73e9de15"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "7d36a897bacf5885a3d774f4ab319e2cb68cb470f6c2ce385f13a55d2bfcaa52"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "5778978b299e4a6d7074ed18f628e0b3cee17c12"
os = "freebsd"

    [[Ninja.download]]
    sha256 = "1a2c2fac43f0dbccb77197a076f02bd19bef12cc2df71f0bab0342c67e0d14fd"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-unknown-freebsd.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd19fa9179c64d3ff643c87f2640ed003e877534"
os = "windows"

    [[Ninja.download]]
    sha256 = "92c176b757ee2187577b4f21e32bd8b5842291958c670e90cfa3f443ecfb4f8d"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95dc8d51ee95089858ea7bd02edb2fd262a0ac8a"
os = "windows"

    [[Ninja.download]]
    sha256 = "a6a3abd44133fce3399a2b9fc14bd78cb4a55d410088cdd8bac1fc48dbccb5f9"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.1+0/Ninja.v1.10.1.x86_64-w64-mingw32-cxx11.tar.gz"
