[[Ninja]]
arch = "aarch64"
git-tree-sha1 = "108acd2afa3a0f34807604fbe4413de237b24adf"
os = "macos"

    [[Ninja.download]]
    sha256 = "7a84abf2e6068671edd1ab584ea48603a8d476d92f167291ea3d8fa2ada6eb61"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.aarch64-apple-darwin.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cf330c1f23c9f385a57b784dc86716ee2a6b2b8"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "840c73a9a88ec182937463129b5e489c88f79e9763bc6cd766659b7a9c47540c"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "655906a0a5eefbf70612e20a108d6de08980aefd"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "8ca3316460b67086ce7f808e08d3d782a1cca8b13ac7fe2cd81a052ac1a4b962"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be92540dfe6d8b22f067a291702665263aad8e9"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "c002951441e92d65d660a9c1779507b8b306c84132e4cf3ad234cc0d5052e69a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.aarch64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "022addbb19264992647cdb740ece6b2dbdac05d8"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "eebcbf38e21569457ee4d3aabb7b2b9f521adefc795e75bf08f08b88f4b3e6d9"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.aarch64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa201c2878d4fc2a406adcf9c4d3e1f4d147e43e"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "b7c019520d880196a916b7320752de3e739545f1270c16e2270d8c771dbb6066"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2feabe85364471f60c36d488cf89f1c5af901c1"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "33e36eee2c84fb076b20bd70efdfd148f0db3d39fe7a8ddc81b333d3dc75e066"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af7ba4338a300cda7d3dc37d3033c1088ca3e7d7"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "37d9f59dfcf2a89e8ff8d3232d0730d8393c97a509b5adec468df6073ca8ffb6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8edf3b64b116021b425d4cb4f8b4b75a056b9927"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "555ded43608ba174958afff97494d33d79fe3514b2b46a4012cae45380c6aa94"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43fcc877b604d6a00f5ab6033fa018c9c4c64032"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "08f4453ed28820d3e89f98d2ecbea12c22a2666c857c00ac1c3968682a0c1288"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a769016f56b26611366fe83ed46cd9843a400da2"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "8da91502147404b4c48a4a974f649abacf8ca25abf2e41c6f592b4852d03a4ad"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1e536ede5e2849c00de8877ace9024e63f4cdf7"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "6569468dd910ff53f92e22c57fb76ebdc125a155f42c305dc850c872ae7f582e"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ac06c3d7fbb1478f8092f32642b92d47ab019c9"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "eff8d8f4a48add9c7468a415af81e604adf0777a1a759c352916eab870866234"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4883c258f992cba41f1d4732870646509d49eb3"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "9e0f471b51e4dfb54326fe71ddf3bbd4184678364724f21645becea163ad3fd6"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.i686-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d039109e9a5cacceceaa0776b19ba64dab160dc1"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "756569ee641ab9066af83e4ac36266d672ceeffcdead6efbff37bf499559653b"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.i686-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c87f10d8e69a4a9aa4d94f935a7090e933e2d848"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "9eda95ba3a217ea190dfe9d557c4db5053fb76e1b8ca5368d0af53d32e259083"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.i686-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1d568d6535bee8228a9769add55bb88313422bb"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "6fc95151505bbe18536b2034f0cd053edadfcbf5f3010e02806b168454fe3953"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.i686-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34cea790702a4591aaa68596f9206dae032fb949"
os = "windows"

    [[Ninja.download]]
    sha256 = "d0b374a87ec5ced8d2cd6e669b01d970453b8bc09f0738c210847e184d6a6c42"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.i686-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb7c822ced5c0fbfd2f71e2678e1a2a586f4d74d"
os = "windows"

    [[Ninja.download]]
    sha256 = "b62467eb261761364f3ac90dcad5a7bac0a6e94d9ae43fe9b51d98860ee44563"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.i686-w64-mingw32-cxx11.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f9e069dbc7a72bce60caa124ab26f57cf2d69fe"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "789aa0ae12b39419d5e4cf9cd0c6d0bb27abee23b9be4054e3a162e992b1f7a5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6825651441c9ec656c5df63969f73c3e39da2ce"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "8671b53b3453dd6be22e560726eb845c8a90e7edc4b99e0d285a92e5d424f67f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "7cb2c2cfc7287dba4e733862932c0e242bbd2814"
os = "macos"

    [[Ninja.download]]
    sha256 = "5da1ac73ed028fd2eff5d6ae6cc0ea8b3563971c4a2565f322e72c914f33cde1"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-apple-darwin.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0368f4411a3499154980ae51593fd4721b140217"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "2fd872968374df3c12051c3c7a613c31dda1cbcdb6fcf9c959fa7156a5c885a2"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e62c00e1f15f21da3a56196bac84e23e6d629c3"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "dc7e205120e2d5d684e0310afde641f0f242d765732e760387444de1f7db1fc9"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "792101cd8678a9a28cb035c9f6c0b474218f87aa"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "c118d64c779ea61658f9758eb87f4f5998a72ddd74bbaedf004e597096b6c1a4"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf6953682ae1ec0a53c905beb4448cb4898f74e4"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "62f136c11da6a5a9bd5329845f0bd21c026db9c27d77477b9a9d29a92ea0bec8"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "e62e2163f5534278e8f7fdc65aa8000e1c3fde1a"
os = "freebsd"

    [[Ninja.download]]
    sha256 = "2224a324fe4f455b0d0545f91a6555d87895d42e3e20c87ae36947c5899e73e5"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-unknown-freebsd.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cc610b6ec5ed3013d2ffd58ea9f03436cce5f23"
os = "windows"

    [[Ninja.download]]
    sha256 = "5ebcdd49f2022e58d71a8e555eb871aeb585450e9d51163e6aad1a7b8052acc4"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc974f23fc5cd28fe1f735a60fa7604901f9f568"
os = "windows"

    [[Ninja.download]]
    sha256 = "f47a1ff3b081fad0f2d58998158b48c3dd63356efdabccd5d0ce89ccc3b70ccf"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.12.1+0/Ninja.v1.12.1.x86_64-w64-mingw32-cxx11.tar.gz"
