[[Ninja]]
arch = "aarch64"
git-tree-sha1 = "dd9ea1fb540fa1900a2425bf40c21e1b5dc700f7"
os = "macos"

    [[Ninja.download]]
    sha256 = "cebc855e459547d962fc75582400aed37581caebacd6ddb523a462b669d87fa1"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.aarch64-apple-darwin.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d3cf0976158f2f51cffa68b853f18cf7e3f2b72"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "08ec75badda55538f330753c20708dc2a591ee51e171df0b19fb7bb39aa5c480"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a685103c7d162f99f6bd3bbc1a310534ddffbc3"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "1d10fc740c5ed9babf659f08281fa5a4ac2c8b3c8252aa4dea7ee6f5b39e4740"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5f713546c2d9cfb17eab0ae2931675b117083a7"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "d9ad526e6da5c32552dd92f46ebcd2df51539e53794877560d72cec602378beb"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.aarch64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2d36ad998b0aa59d7addfc800380c71c014bc50"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "7a7f658de0eff2ae96a365c8089df8cbd50f336e1d893859321c86a819396f1e"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.aarch64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04b494ee201fb57be095ee0c4a38f5ac1bd050a2"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "29e20b98751b13ec0efda2787e9d0914fe2c93e7a672dd13b398638e5c880788"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4a994d64eea3ff93580b027d65184812d6e1266"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "0baf782798924f8ef4adc24d95b42a175708cd65bba85c757b564427300033e9"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53f1a6e1f557806785f1c23e4bdff0a785b01246"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "6b25df42c2d69c2272578048dece9837c8b7b73cd61548c5c434b9440481ce26"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94ddde121a1fb75fbecd7dea6a926c16b2a53d6b"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "a581409c43b6e3141fb6e3f2c31442f7b3897f27c662dfd5bf38a11669a1f531"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b06e24692dcd6ecbde930f90b9b99a5f87e87c8"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "9001f612753ce9a704f13ebe45f9078cfba68ee9a8f2c485a575d14db6d07df4"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b36c95ef9213de249df41b056c694dbf22ee4fdc"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "909f334c37ef1bd1a2a4fdbbfd5f343e91f6f6d42d979f8de91a3c74a3d236e3"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "431ea39c2f9fc6e34cade78d53d7d3d9ed624d32"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "b3c1d82eb47a696674a81382c127730e8242117d05397d22d51db1c0dcc5c488"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ninja]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "515449716a065285cc671693ceae11272cd716b9"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "1cf28e0b2be578666bba07f6e400b3b76b1c23ff4c823317a4c91cbb467805cf"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ebb170b602b35a19b8bad64ba2c8a98b632620d"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "156bfd1342e87a82fbfc2ea38301a1b06061357dceecf74f2057d3f01a58def7"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.i686-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ee3e80f8d0fddcad14270957c764b4ac25bb4fe"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "c7ebf3ecec9d7f120f19c35d623a2c0dbcf3f90179fdf78227037e1702689f27"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.i686-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abaec61976dc79df8d527b318b0b62e114a171d1"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "1b593044338941eebc61a29b38483ff87798182b600aab8a1699bb583ca033ae"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.i686-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5c1177dd5b7d30857c3d1bdba01b332a55224ba"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "7c5936926f789f2592d4a2b807bf9f1419b9647be2ab056268d77154302d8161"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.i686-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4e92d7f9d612b33aa3cf4a90bc96ec922a5ab0e"
os = "windows"

    [[Ninja.download]]
    sha256 = "b34c4285e7879eac6f57c1687e18051db93b8b7d1780bf286a9e3664b2be546a"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.i686-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "208f9cb7f19e7a09ec45e3c9ff3ec3f20108e262"
os = "windows"

    [[Ninja.download]]
    sha256 = "b2e61caddc674bfd4849264e5382e5669ca68e8def1f1357d2cdf81fc9468601"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.i686-w64-mingw32-cxx11.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71e6c522bbecb4416aaf49495b487889a0610f61"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "7a515411e1783b940405cff836be1f281d7ce4e7e969edceea6ccf282516037b"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8c356119abfddd0c82a5f1f06ce249248b72685"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "d8ca896d5f815f6b4f3e70f587520aab6d2ff9bd487fdeb9a04f64e2f6158b7f"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "ade3307b7479db346045d209f3af54ac348005ff"
os = "macos"

    [[Ninja.download]]
    sha256 = "fac9260ec3e5a55d281f86c59de8f15792b40e714ec5db13898aa70fbb055284"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-apple-darwin.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2bdc023fa7ece71dfa1dd41d4941dd346669545"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "cdb694758012d5ef9885191e498e8ad58307abaa445669ce75b597377f35df86"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81c48e74de508ba1b32c3a1fecd7f019f4a1a519"
libc = "glibc"
os = "linux"

    [[Ninja.download]]
    sha256 = "9aa028b3746ce69b34b797d611a051b2a41588c512184fd4495b1bb63db58892"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10c5edc895df5c081b56e01f5b59768c9466f772"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "2488cbee21b7926762b386f2f6863e74a0d0960e5c68da59b53244e4254ff917"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-linux-musl-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4743ef510393677ceafed09173fb4392a5ff19f5"
libc = "musl"
os = "linux"

    [[Ninja.download]]
    sha256 = "21638471133d6de2b18fee2b99e3d7b656ab62b6a5f291a1dbeed93b91ebf153"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-linux-musl-cxx11.tar.gz"
[[Ninja]]
arch = "x86_64"
git-tree-sha1 = "e598330679f210ec37cae46a699ce29e29158690"
os = "freebsd"

    [[Ninja.download]]
    sha256 = "b38bbcc602f0ef7a6076f2ffe01f9d454894a36086d81831105b9f7b48451f24"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-unknown-freebsd.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d5fc9af3f66cf5d40d505a3ba9014dd6467a105"
os = "windows"

    [[Ninja.download]]
    sha256 = "a2483953405845ca69e29d8f2d42f2d893c264ddccb73b35c88f0cf532aae687"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ninja]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7c97fa335bdcf639cf3801c2f0affda9545cbd6"
os = "windows"

    [[Ninja.download]]
    sha256 = "9a8e9e7748513d99fc0b41b95a4578850b1ae160a94849a75e217de6650861c0"
    url = "https://github.com/JuliaBinaryWrappers/Ninja_jll.jl/releases/download/Ninja-v1.10.3+0/Ninja.v1.10.3.x86_64-w64-mingw32-cxx11.tar.gz"
